name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js (Latest LTS)
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Install external dependencies (imagemagick & friends)
      run: sudo apt-get install -y imagemagick ghostscript graphicsmagick
    - run: npm i
    - run: npm test
